### ISSUE TITLE
FAAD2 broken

### ISSUE THREAD

**Issue by aargirakis** [aargirakis/BZRPlayer#141]
The lib for AAC is not working properly

**Comment by ciros88** [comment]
@aargirakis it has been completely fixed in 2.0.48.Alpha? how i can test it?

**Comment by aargirakis** [comment]
No not fixed, but most (I think) .aac files work. (Not mp4 with aac)

**Comment by ciros88** [comment]
i've tested faad2 with its own sample files (attached):

2.0.19: some files playback weird and others make it crash
2.0.30: even more files playback weird and even more others make it crash (compared to older bzr2 versions)
2.0.70: even more files playback weird and even more other makes it (compared to older bzr2 versions)

briefly: it has been getting worse over time

rename mp4_1.7z.zip & mp4_2.7z.zip extension to 7z:
[aac_1.zip](https://github.com/user-attachments/files/16024814/aac_1.zip)
[aac_2.zip](https://github.com/user-attachments/files/16024816/aac_2.zip)
[m4a_1.zip](https://github.com/user-attachments/files/16024818/m4a_1.zip)
[m4a_2.zip](https://github.com/user-attachments/files/16024834/m4a_2.zip)
[m4a_3.zip](https://github.com/user-attachments/files/16024838/m4a_3.zip)
[mp4_1.7z.zip](https://github.com/user-attachments/files/16024840/mp4_1.7z.zip)
[mp4_2.7z.zip](https://github.com/user-attachments/files/16024841/mp4_2.7z.zip)
