### ISSUE TITLE
GUI freezes when trying to play smpl files

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#65]
this happens only if playlist contains the correspondent mdat file. when playlist contains only smpl files then no freezing occurs

#122 could be a good solution

**Comment by aargirakis** [comment]
Are you sure that the smpl-file isn't the last in the playlist? Because I get no crash/freeze

**Comment by ciros88** [comment]
yeah, the bug occours when playlist ends with a smpl file (no matter if it is the one related to just played mdat or another one).
to reproduce:
i've made a playlist with relative paths (one day also this aspect should be handled):
[playlist.zip](https://github.com/aargirakis/BZRPlayer/files/9486923/playlist.zip)
open in bzr2, play one of mdats entries, then try to playing one of smpl entries, no matter which

**Comment by aargirakis** [comment]
Try to add just a playable file to the end of your playlist and it wil be fine. This is the same bug as when it crashes if the last song in the playlist is unplayable. But I can't find that issue now though?

**Comment by ciros88** [comment]
if you refer to issue #5 , it was about crash when trying to play an invalid files, and this one was the last entry in playlist: it has been resolved (closed). this issue it's a little different: the crash here happens if trying to play one of the playlist smpl, no matter if is the last entry or not.
but yeah, the resolution is the same: putting a valid track to the end will prevent crashing.

**Comment by aargirakis** [comment]
Actually, #5 is not fixed AFAIK. So I opened it again, and this is the same bug AFAIK.
